name: Ansible deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
    - name: Install ansible
      run: |
        sudo apt-get update
        sudo apt-get install ansible
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Install artushak-static-web-packer
      # TODO: publish this crate to to crates.io
      run: cargo install --git https://github.com/ArtUshak/artushak-static-web-packer.git
    - name: Build static website
      run: artushak-static-web-packer
    - name: Deploy using ansible
      run: |
        ansible-playbook -i ansible/inventory ansible/deploy.yml
